# Base our tests on the tools image
FROM docker.io/ethcomsec/cellift-chipyard-base:cellift-chipyard-base
WORKDIR /cellift-designs/cellift-chipyard/sims/verilator
RUN bash -c ". ../../../../cellift-meta/env.sh ; make CONFIG=MySmallBoomConfig"
WORKDIR /cellift-designs/cellift-chipyard/cellift-boom
CMD bash tests.sh
