# Base our tests on the tools image
FROM docker.io/ethcomsec/cellift:cellift-tools-main
COPY . /cellift-designs/chipyard
WORKDIR /cellift-designs/chipyard/
RUN bash ./scripts/init-submodules-no-riscv-tools.sh --skip-validate
WORKDIR /cellift-designs/chipyard/cellift-boom
CMD bash tests.sh
