# Base our tests on the tools image
FROM docker.io/ethcomsec/cellift:cellift-tools-main
COPY . /cellift-designs/cellift-chipyard
WORKDIR /cellift-designs/cellift-chipyard/
RUN bash ./scripts/init-submodules-no-riscv-tools.sh --skip-validate
