RESOURCEWRAPPER_TAG = boom
DESIGN_NAME = boom

REPLACE_BOOTROM ?= 0

TOP_MODULE = boom_mem_top # Top module for the Yosys instrumentation.

DESIGN_CONFIG = MySmallBoomConfig

include ../cellift-common/cellift-common.mk
