RESOURCEWRAPPER_TAG = rocket
DESIGN_NAME = rocket

REPLACE_BOOTROM = 0

TOP_MODULE = rocket_mem_top # Top module for the Yosys instrumentation.

DESIGN_CONFIG = MySmallVMRocketConfig

include ../cellift-common/cellift-common.mk
